### ISSUE TITLE
Trouble running testbench locally

### ISSUE THREAD

**Issue by gitonthescene** [reconciliation-api/testbench#42]
```Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/private/tmp/testbench/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/private/tmp/testbench/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/private/tmp/testbench/node_modules/webpack/lib/NormalModule.js:449:10)
    at /private/tmp/testbench/node_modules/webpack/lib/NormalModule.js:481:5
    at /private/tmp/testbench/node_modules/webpack/lib/NormalModule.js:342:12
    at /private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/private/tmp/testbench/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /private/tmp/testbench/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
/private/tmp/testbench/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/private/tmp/testbench/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/private/tmp/testbench/node_modules/webpack/lib/NormalModule.js:401:16)
    at /private/tmp/testbench/node_modules/webpack/lib/NormalModule.js:433:10
    at /private/tmp/testbench/node_modules/webpack/lib/NormalModule.js:308:13
    at /private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/private/tmp/testbench/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /private/tmp/testbench/node_modules/babel-loader/lib/index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.0.0
```
The workaround [here](https://github.com/webpack/webpack/issues/14532) seemed to fix it.

FWIW, I'm running on OSX 12.0.1 with npm version 8.6.0.

**Comment by gitonthescene** [comment]
When running the testbench locally and selecting *Add a Service* you still get the following warning:
 > Make sure your service is publicly accessible - local endpoints (such as those with localhost or 127.0.0.1 in their address) should not be added to this table.

along with instructions on updating some SPARQL query.  It's not clear if this is appropriate for testing a service in development or exactly what would be tested of a service in development.

**Comment by wetneb** [comment]
>  It's not clear if this is appropriate for testing a service in development or exactly what would be tested of a service in development.
ah yeah, perhaps we should improve this message with something like: "If you want to test a service you are developing, click the "Test bench" tab at the top of this page."

Would that help?

**Comment by gitonthescene** [comment]
I’ll try it and report back.
